import { Doctor } from '../types/doctor';

// Helper function to generate random availability slots
const generateAvailability = () => {
  const times = [];
  const startHour = 8 + Math.floor(Math.random() * 2); // 8 or 9 AM start
  const intervals = ['00', '30'];
  
  for (let i = 0; i < 4; i++) {
    const hour = startHour + i * 2;
    const time = `${hour > 12 ? hour - 12 : hour}:${intervals[Math.floor(Math.random() * 2)]} ${hour >= 12 ? 'PM' : 'AM'}`;
    times.push(time);
  }
  return times;
};

export const mockDoctors: Doctor[] = [
  {
    id: '1',
    name: 'Dr. Sarah Johnson',
    specialty: 'Cardiology',
    rating: 4.8,
    location: 'Main Hospital, Floor 3',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/65.jpg',
  },
  {
    id: '2',
    name: 'Dr. Michael Chen',
    specialty: 'Cardiology',
    rating: 4.6,
    location: 'Cardiac Center, Floor 2',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
  },
  {
    id: '3',
    name: 'Dr. Emily Wilson',
    specialty: 'Cardiology',
    rating: 4.9,
    location: 'Heart Institute, Floor 1',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
  },
  {
    id: '4',
    name: 'Dr. Robert Garcia',
    specialty: 'Cardiology',
    rating: 4.7,
    location: 'Main Hospital, Floor 3',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/75.jpg',
  },
  {
    id: '5',
    name: 'Dr. Lisa Park',
    specialty: 'Cardiology',
    rating: 4.5,
    location: 'Cardiac Center, Floor 1',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/33.jpg',
  },
  {
    id: '6',
    name: 'Dr. David Kim',
    specialty: 'Neurology',
    rating: 4.7,
    location: 'Neuro Center, Floor 4',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/22.jpg',
  },
  {
    id: '7',
    name: 'Dr. Jennifer Lee',
    specialty: 'Neurology',
    rating: 4.9,
    location: 'Main Hospital, Floor 4',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/28.jpg',
  },
  {
    id: '8',
    name: 'Dr. James Wilson',
    specialty: 'Neurology',
    rating: 4.6,
    location: 'Neuro Center, Floor 3',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
  },
  {
    id: '9',
    name: 'Dr. Maria Rodriguez',
    specialty: 'Neurology',
    rating: 4.8,
    location: 'Main Hospital, Floor 4',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/50.jpg',
  },
  {
    id: '10',
    name: 'Dr. Thomas Brown',
    specialty: 'Neurology',
    rating: 4.5,
    location: 'Neuro Center, Floor 2',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/60.jpg',
  },
  {
    id: '11',
    name: 'Dr. Amy Smith',
    specialty: 'Pediatrics',
    rating: 4.9,
    location: "Children's Center, Floor 1",
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/30.jpg',
  },
  {
    id: '12',
    name: 'Dr. Kevin Patel',
    specialty: 'Pediatrics',
    rating: 4.7,
    location: "Children's Center, Floor 2",
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/25.jpg',
  },
  {
    id: '13',
    name: 'Dr. Olivia Martin',
    specialty: 'Pediatrics',
    rating: 4.8,
    location: 'Main Hospital, Floor 1',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/35.jpg',
  },
  {
    id: '14',
    name: 'Dr. Daniel Kim',
    specialty: 'Pediatrics',
    rating: 4.6,
    location: "Children's Center, Floor 1",
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/40.jpg',
  },
  {
    id: '15',
    name: 'Dr. Sophia Chen',
    specialty: 'Pediatrics',
    rating: 4.9,
    location: 'Main Hospital, Floor 1',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/42.jpg',
  },
  {
    id: '16',
    name: 'Dr. Richard Davis',
    specialty: 'Orthopedics',
    rating: 4.7,
    location: 'East Wing, Floor 1',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/55.jpg',
  },
  {
    id: '17',
    name: 'Dr. Emma Wilson',
    specialty: 'Orthopedics',
    rating: 4.8,
    location: 'Sports Medicine Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/48.jpg',
  },
  {
    id: '18',
    name: 'Dr. Christopher Lee',
    specialty: 'Orthopedics',
    rating: 4.6,
    location: 'East Wing, Floor 1',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/35.jpg',
  },
  {
    id: '19',
    name: 'Dr. Jessica Brown',
    specialty: 'Orthopedics',
    rating: 4.9,
    location: 'Sports Medicine Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/55.jpg',
  },
  {
    id: '20',
    name: 'Dr. Matthew Taylor',
    specialty: 'Orthopedics',
    rating: 4.5,
    location: 'East Wing, Floor 2',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/65.jpg',
  },
  {
    id: '21',
    name: 'Dr. Rachel Green',
    specialty: 'Dermatology',
    rating: 4.8,
    location: 'Skin Care Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/60.jpg',
  },
  {
    id: '22',
    name: 'Dr. Andrew Scott',
    specialty: 'Dermatology',
    rating: 4.7,
    location: 'Main Hospital, Floor 2',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/50.jpg',
  },
  {
    id: '23',
    name: 'Dr. Natalie King',
    specialty: 'Dermatology',
    rating: 4.9,
    location: 'Skin Care Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/65.jpg',
  },
  {
    id: '24',
    name: 'Dr. Ethan Wright',
    specialty: 'Dermatology',
    rating: 4.6,
    location: 'Main Hospital, Floor 2',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/70.jpg',
  },
  {
    id: '25',
    name: 'Dr. Victoria Adams',
    specialty: 'Dermatology',
    rating: 4.7,
    location: 'Skin Care Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/70.jpg',
  },
  {
    id: '26',
    name: 'Dr. Benjamin Clark',
    specialty: 'Ophthalmology',
    rating: 4.8,
    location: 'Eye Care Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/45.jpg',
  },
  {
    id: '27',
    name: 'Dr. Samantha White',
    specialty: 'Gastroenterology',
    rating: 4.7,
    location: 'Digestive Health Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/40.jpg',
  },
  {
    id: '28',
    name: 'Dr. Nathan Hill',
    specialty: 'Psychiatry',
    rating: 4.9,
    location: 'Mental Health Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/55.jpg',
  },
  {
    id: '29',
    name: 'Dr. Grace Turner',
    specialty: 'Endocrinology',
    rating: 4.6,
    location: 'Diabetes Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/45.jpg',
  },
  {
    id: '30',
    name: 'Dr. Patrick Moore',
    specialty: 'Rheumatology',
    rating: 4.7,
    location: 'Arthritis Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/men/60.jpg',
  },
  {
    id: '31',
    name: 'Dr. Lauren Young',
    specialty: 'Family Medicine',
    rating: 4.8,
    location: 'Primary Care Center',
    availability: generateAvailability(),
    photoUrl: 'https://randomuser.me/api/portraits/women/35.jpg',
  }
];

export const specialties = [
  'All Specialties',
  'Cardiology',
  'Neurology',
  'Pediatrics',
  'Orthopedics',
  'Dermatology',
  'Ophthalmology',
  'Gastroenterology',
  'Psychiatry',
  'Endocrinology',
  'Rheumatology',
  'Family Medicine'
];